drop table if exists cliente_vehiculo CASCADE;
drop table if exists clientes CASCADE;
drop table if exists detalle_ordenes_trabajo CASCADE;
drop table if exists empleados CASCADE;
drop table if exists mano_obra CASCADE;
drop table if exists mecanicos CASCADE;
drop table if exists ordenes_trabajo CASCADE;
drop table if exists repuestos CASCADE;
drop table if exists vehiculos CASCADE;

 create table cliente_vehiculo (
       cliente_id bigint not null,
        vehiculo_id bigint not null
    );


    create table clientes (
       id bigint generated by default as identity,
        apellido varchar(80) not null,
        calle varchar(255),
        celular varchar(15),
        codigo_postal varchar(255),
        departamento varchar(255),
        correo_electronico varchar(255),
        localidad varchar(255),
        nombres varchar(100) not null,
        numero varchar(255),
        piso varchar(255),
        telefono_linea varchar(15),
        primary key (id)
    );


    create table detalle_ordenes_trabajo (
       id bigint generated by default as identity,
        cantidad integer,
        valor_total double,
        orden_trabajo_id bigint,
        repuesto_id bigint,
        primary key (id)
    );


    create table empleados (
       id bigint generated by default as identity,
        apellido varchar(255),
        calle varchar(255),
        celular varchar(15),
        codigo_postal varchar(255),
        departamento varchar(255),
        localidad varchar(255),
        nombres varchar(255),
        numero varchar(255),
        piso varchar(255),
        tipo_empleado varchar(255),
        primary key (id)
    );


    create table mano_obra (
       id bigint generated by default as identity,
        detalle varchar(255),
        duracion_hs timestamp,
        mecanico_id bigint,
        orden_trabajo_id bigint,
        primary key (id)
    );


    create table mecanicos (
       id bigint generated by default as identity,
        activo char(255),
        apellido varchar(255),
        calle varchar(255),
        celular varchar(15),
        codigo_postal varchar(255),
        departamento varchar(255),
        especialidad varchar(255),
        localidad varchar(255),
        nombres varchar(255),
        numero varchar(255),
        piso varchar(255),
        primary key (id)
    );


    create table ordenes_trabajo (
       id bigint generated by default as identity,
        cantidad_cuotas integer,
        estado varchar(255),
        detalle_falla varchar(255),
        fecha_pago date,
        fecha_fin_reparacion date,
        forma_pago varchar(255),
        importe_total double,
        fecha_ingreso date,
        kilometraje bigint,
        nivel_combustible varchar(255),
        tipo_tarjeta varchar(255),
        administrativo_id bigint,
        recepcionista_id bigint,
        vehiculo_id bigint,
        primary key (id)
    );


    create table repuestos (
       id bigint generated by default as identity,
        marca varchar(255),
        modelo varchar(255),
        repuesto varchar(255),
        valor double,
        primary key (id)
    );


    create table vehiculos (
       id bigint generated by default as identity,
        anio integer,
        color varchar(255),
        marca varchar(255),
        modelo varchar(255),
        patente varchar(255),
        primary key (id)
    );


    alter table clientes
       add constraint UK_f90r5ev5hwm529n393c92294x unique (correo_electronico);


    alter table vehiculos
       add constraint UK_kxt53tfqxxydvqll7ldil6qu7 unique (patente);


    alter table cliente_vehiculo
       add constraint FK2ufsrlqafc9q4ww208bq2ejpq
       foreign key (vehiculo_id)
       references vehiculos;


    alter table cliente_vehiculo
       add constraint FKispl4o9vyqm2bbpyle5y4dcx5
       foreign key (cliente_id)
       references clientes;


    alter table detalle_ordenes_trabajo
       add constraint FK2xbsyaw7n3a5xqd4ecpmjy0u2
       foreign key (orden_trabajo_id)
       references ordenes_trabajo;


    alter table detalle_ordenes_trabajo
       add constraint FKdqnjjclygimbajtq306sto0te
       foreign key (repuesto_id)
       references repuestos;


    alter table mano_obra
       add constraint FKp4lvtoc1ldrxkt9k0xcl5dsyd
       foreign key (mecanico_id)
       references mecanicos;


    alter table mano_obra
       add constraint FKtbkk8levawgkr8yek4jiac6t1
       foreign key (orden_trabajo_id)
       references ordenes_trabajo;


    alter table ordenes_trabajo
       add constraint FK3j37bsnw2ov9bdw008cso6btr
       foreign key (administrativo_id)
       references empleados;


    alter table ordenes_trabajo
       add constraint FK9k57to63n1igtba7n6m19ri4t
       foreign key (recepcionista_id)
       references empleados;


    alter table ordenes_trabajo
       add constraint FK8tmipf5cufvljctlbrcqt3ojt
       foreign key (vehiculo_id)
       references vehiculos;